# Generated by Django 3.0.4 on 2020-07-25 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='hospital',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
