# Generated by Django 3.0.4 on 2020-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0003_auto_20200725_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontier_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
